### ISSUE TITLE
Logging should be configurable and optional

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#13]
At the moment logging is hardcoded to use "./log/info.log" and "../log/error.log". This is a bit inconsistent generally, but that's somewhat parallel to a larger question imo: 

* Logging should be optional- if someone wants to use bundler without any logging it should be doable. 
* We should be able to pass the location that the logs are written to

**Comment by redwire** [comment]
This will actually be kind of a pain to implement because every module that uses the Winston logger has a different instance.  I'll try to make it possible to turn off logging at the very least.

**Comment by redwire** [comment]
I just finished trying all sorts of things to disable logging at different levels across all the modules and found nothing worked.  Even calling `log.remove(<log name>)` in every module didn't stop logging from occurring.  In https://github.com/equalitie/bundler/commit/c8387c7c8aeea61267eaca173912d7588ecfccf7 I have removed all forms of logging until I can come up with a better logging scheme.

**Comment by nosmo** [comment]
I got the impression that this would be kinda messy - could we use module.exports to share the logger globally?

**Comment by redwire** [comment]
I spend a lot of time trying to get this approach to work, as you can see in https://github.com/equalitie/bundler/commit/6b166a8b540d044275ac45df060f42ea5627e8ea but didn't get anywhere near where we want to be.

**Comment by redwire** [comment]
I have spent yet more time thinking about how we could feasibly accomplish what you're asking for and I don't think there's any real way to do it without writing a ton of obnoxious, bloated logging code.  I've also scanned through the code in request.js as a reference and found that it, like many libraries, don't do any logging at all.  I think this kind of makes sense, myself, since the library _should_ provide a stable and correct implementation of the functionality it provides.  Perhaps rather than rigorous logging, I can write more tests and simply insert log calls as they're needed for dev. purposes.

With that all said, I have a suggestion.  I could write helper functions that could be set on certain events to make it easy for users of the bundler library to write their own logging between events.  I think this would capture most of the use cases we really care about as far as usability of the bundler library goes, and we're really more interested in what the specific handlers the proxy server is using are doing anyway.

What do you think @nosmo ?

**Comment by nosmo** [comment]
I think you're right as regards removing logging altogether. Personally I don't think logging within libraries is a good idea generally, but in some cases it's unavoidable. Now that we have split the proxy server off into its own repo I think it makes sense to, as you said, simply focus all logging within the proxy server itself. If you feel that writing the helper functions is a reasonable use of your time then go for it, otherwise simply stripping out logging is okay with me.
