### ISSUE TITLE
Using a remap to retrieve learn.equalit.ie via Bundler results in a parsing failure that breaks bundling

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#16]
Fetcing the following using the bundler-proxy works fine: http://127.0.0.1:9008/?url=http://learn.equalit.ie/wiki/Main_Page

However, when using a remap that points learn.distributed.deflect.ca at learn.equalit.ie's origin (contact me off-thread for the IP address), I get some really weird behaviour which ultimately results in a 500 error. Some debugging and checking the logs on the origin reveals that Bundler is attempting to fetch the following files: 

```
[10/Apr/2015:17:33:55 +0200] "GET /mw/)!ie}.mw-help-field-data{display:block;background-color: HTTP/1.1" 301 625 "-" "-"
[10/Apr/2015:17:33:55 +0200] "GET /mw/)!ie;background-position:left%20center;background-repeat:no-repeat;cursor:pointer;font-size:.8em;text-decoration:underline;color: HTTP/1.1" 301 783 "-" "-"
[10/Apr/2015:17:33:55 +0200] "GET /mw/)%20} HTTP/1.1" 301 516 "-" "-"
```

This appears to be a failure to finish loading or encoding style sheets or something of the sort. 

Why would Bundler be behaving differently when in theory all that should have changed is the Host header and the URL?

**Comment by redwire** [comment]
I'll investigate this. I'm going to need those IP addresses though.
I've messaged you on IRC. Please get back to me as soon as you can.

**Comment by redwire** [comment]
I have been unable to recreate the bug you've described here.
Bill got the IP address you mentioned from the server you have been using to do your testing, so I was able to create the remapping `"learn.distributed.deflect.ca": "<IP address>"` in `remaps.json`.  I effectively  copied the proxy server code into the test directory of the bundler library code so that I'd be testing with the latest version of the bundler.
I was able to verify that learn.equalit.ie/wiki/Main_Page is indeed bundled and served properly.
When I tried to get a bundle for learn.distributed.deflect.ca, using the bundler proxy, I found I was only served a page with a redirect to a wiki. The request to go to the wiki obviously fails because it is not of the `localhost:9008?url=<url>` format, but when I printed the contents of the received bundle for learn.distributed.deflect.ca, I just saw the redirect page. In other words, I'm not detecting any kinds of erroneous behavior.
I think this redirecting is something new that wouldn't have affected your tests are there any other sites/remappings that cause this bug?

**Comment by redwire** [comment]
To report, I've found that the following code works:

```javascript
var ip = [REDACTED]; // The IP of the origin of learn.equalit.ie
request({
  url: 'http://' + ip + '/wiki/Main_Page', 
  headers: { 'Host': 'learn.distributed.deflect.ca' }
}, function (err, res, body) {
  console.log(body.toString());
});
```

So at the very least, the plain old request isn't failing. We're able to get around the wiki page redirect when we have this remapping in place.

**Comment by nosmo** [comment]
Sorry, this is partially a result of me not being fully clear as to what I was seeing - I get the redirect without issue, and when served behind a reverse proxy responsible for a domain the redirect behaviour is correct. Where bundling fails is for this specific URL (the final destination of the redirects): http://127.0.0.1:9008/?url=http://learn.distributed.deflect.ca/wiki/Main_Page

**Comment by redwire** [comment]
I'm still not sure I'm seeing the problem you are having.  At this time, while I'm testing it after having pushed my recent commits to bundler-proxy (and testing the actual bundler proxy and not bundler- this issue should really be under bundler-proxy, by the way), I don't seem to be having an issue.

From what I can see from the output of bundler-proxy, all the URLs for resources are well formed- there aren't any weird parsing errors going on. The page requested is being bundled just fine and served in full.  I have noticed, when I navigate to http://127.0.0.1:9008/?url=http://learn.equalit.ie/wiki/Main_Page  in my browser, I'm getting a 404 page. Probably not what we want, but it's better than an error. I get the same thing with CURL.

When I navigate run `curl http://127.0.0.1:9008/?url=http://learn.distributed.deflect.ca/wiki/Main_Page`, I get the following:
```html
<HTML>
<HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Access Denied</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: You are not allowed to access the document you requested.
</B></FONT>
<HR>
</BODY>
```
just as in https://github.com/equalitie/bundler-proxy/issues/2

**Comment by nosmo** [comment]
Also related to https://github.com/equalitie/bundler-proxy/issues/2, not specifically an issue.
