### ISSUE TITLE
Resource bundling for non-external resources?

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#18]
I'd like a way to configure the bundling of non-local resources to the requested domain. Currently if I fetch site.com and site.com has a resource on gstatic.com (let's say), the resource on gstatic.com will be bundled. This is obviously great for CeNo!'s purposes, but for DDeflect this is not optimal - I'd like a means to specify that if I ask for site.com, only resources under site.com be bundled.

**Comment by redwire** [comment]
Okay! I will get on this!

**Comment by redwire** [comment]
I've done a few things to satisfy this request.

1. I wrote the [predicated](https://github.com/equalitie/bundler/blob/master/src/handlers.js#L19) handler/helper that allows you to augment calls to handlers so that bundler only invokes them if a provided predicate passes.
2. I wrote a predicate for [testing that a resource is on the same host as the original document](https://github.com/equalitie/bundler-proxy/commit/ec494ba1c7de973f681cfb314e2b25e039ea4f0f) and provided (commented) code that augments each of the major handlers.
3. I wrote a URL replacer that will [filter only URLs for resources on the same host as the original document](https://github.com/equalitie/bundler-proxy/commit/3c8faf0e3c6448393c64f251132a4137c484f57c) and included a (commented) call to it at the start of the proxy's handler list.
